# Generated by Django 4.1 on 2022-08-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0011_alter_concursante_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursante',
            name='juez1',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5, verbose_name='juez1'),
        ),
        migrations.AddField(
            model_name='concursante',
            name='juez2',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5, verbose_name='juez2'),
        ),
        migrations.AddField(
            model_name='concursante',
            name='juez3',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5, verbose_name='juez3'),
        ),
    ]
