# Generated by Django 4.1 on 2022-08-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0012_concursante_juez1_concursante_juez2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concursante',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='concursante',
            name='total',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5, verbose_name='total'),
        ),
    ]
